info_collector.exe: info_collector.cpp increment_date.cpp increment_date.h
	g++ info_collector.cpp increment_date.cpp
	
clean:
	rm -f a.out info_collector.cpp.o output.csv
	
debug.o: info_collector.cpp increment_date.cpp increment_date.h
	g++ info_collector.cpp increment_date.cpp
